SELECT * FROM customer LIMIT 20;
--Total revenue generated by male vs female customers 
Select gender, SUM(purchase_amount) as revenue from customer group by gender
--Customer that use discount but purchase amount is greater that the avg purchase amt
Select customer_id, purchase_amount from customer where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)
--Product with top 5 highest average review rating
SELECT item_purchased, Round(AVG(review_rating::NUMERIC), 2) from customer group by item_purchased ORDER BY AVG(review_rating) desc limit 5
--Avg purchase amount between standard and express shipping
Select shipping_type, Round(avg(purchase_amount::numeric)) from customer where shipping_type in ('Express', 'Standard') GROUP by shipping_type 
--Avg amount spent between subscribers and non subscribers
Select avg(purchase_amount), sum(purchase_amount) ,subscription_status from customer group by subscription_status
--Top 5 procducts with highest percentage of products purchased where discount was applied
Select item_purchased,round(100 * SUM(Case when discount_applied = 'Yes' then 1 else 0 end)/count(*) , 2) as discount_rate from customer group by item_purchased order by discount_rate desc limit 5
--Segment customer into new, returning and loyal 
with customer_type as(
  SELECT customer_id, previous_purchases,
  CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
  from customer
)
SELECT customer_segment, COUNT(*) from customer_type GROUP BY customer_segment
--Top 3 most purchased products within each category
SELECT 
    t1.category,
    t1.item_purchased,
    t1.total_purchases
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases
    FROM customer
    GROUP BY category, item_purchased
) t1
WHERE (
    SELECT COUNT(*)
    FROM (
        SELECT 
            category,
            item_purchased,
            COUNT(*) AS total_purchases
        FROM customer
        GROUP BY category, item_purchased
    ) t2
    WHERE t2.category = t1.category
      AND t2.total_purchases > t1.total_purchases
) < 3
ORDER BY t1.category, t1.total_purchases DESC;
--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;